Plot api
lum-ai/odinson pull request #262
Opened 2021-03-01 17:51 UTC by danebell

There are two changes here:
1. Improvements to the `term-freq` endpoint: additional arguments provide (a) a second, conditioning variable to allow two-way counting, and (b) a regular expression string to filter the terms returned.
2. A new endpoint, `term-hist` which returns a frequency table of terms binned either by user specification or by a sensible default dependent on whether the bins should be fixed-width or proportional.

Tests are included.

2021-03-04 19:09 UTC, myedibleenso requested changes

2021-03-04 19:09 UTC, myedibleenso commented on backend/app/controllers/OdinsonController.scala
> +      def isMatch(s: String, filter: Option[String]): Boolean = {
Let's add a docstring to this method.

2021-03-04 19:09 UTC, myedibleenso commented on backend/test/controllers/OdinsonControllerSpec.scala
> +        route(app, FakeRequest(GET, "/api/term-hist?field=lemma").withJsonBody(body)).get
Can we add another test that includes some of the other optional params for this endpoint (ex. log scale)?

2021-03-18 17:57 UTC, danebell commented
I have made the requested changes, and added two endpoints `rule-freq` and `rule-hist` to provide analogous statistical frequency tables to `term-freq` and `term-hist`, respectively.

2021-03-18 20:23 UTC, myedibleenso commented
Thank you, @danebell !

2021-03-18 20:24 UTC, merged