first pass at incremental indexing
lum-ai/odinson pull request #287
Opened 2021-05-12 17:22 UTC by reynoldsm88

@marcovzla @BeckySharp @danebell 

I took a pass at adding incremental indexing to the `OdinsonIndexWriter`. Based on the unit tests this seems to work in theory, however, I have not tested it out in a real application yet. I'll update this thread when I have more information in that regard. The changes are fairly straightforward, however, I'm going to mark one particular change that I need someone with more expertise to evaluate if I did something untoward or not.

2021-05-12 17:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lum-ai/odinson?pullRequest=287) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lum-ai/odinson?pullRequest=287) before we can accept your contribution.<br/><hr/>**Michael Reynolds** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lum-ai/odinson?pullRequest=287) it.</sub>

2021-05-12 17:23 UTC, reynoldsm88 commented on core/src/main/scala/ai/lum/odinson/OdinsonIndexWriter.scala
>    def close(): Unit = {
@marcovzla - can you review the changes to this method? The Lucene methods don't appear to support overwriting or merging existing files, so the only way I could get it to work was to rewrite the file each time...

2021-05-12 20:31 UTC, BeckySharp requested changes
Just went over this with @marcovzla -- looks great!!
We left two small comments/requests amidst our gratitude :)
Also -- travis will cry unless you run the linting step -- 
`sbt scalafmtAll && sbt scalafmtCheckAll`
(http://gh.lum.ai/odinson/contributing.html)

2021-05-12 20:31 UTC, BeckySharp commented on core/src/test/scala/ai/lum/odinson/foundations/TestIndexWriter.scala
> +
@reynoldsm88 to really test this -- can you add a line here that (a) runs a query, you get N results, (b) then you add the new document, (c) and with the same extractor engine, run the same query and you get N + M results?

2021-05-12 20:31 UTC, BeckySharp commented on core/src/main/scala/ai/lum/odinson/OdinsonIndexWriter.scala
> +    if (directory.listAll().contains(VOCABULARY_FILENAME)) directory.deleteFile(VOCABULARY_FILENAME)
can you please add a small comment here to help ppl know why these files are being deleted? thanks!

2021-05-12 20:31 UTC, BeckySharp commented
this is great!

2021-05-17 17:12 UTC, reynoldsm88 commented
https://github.com/lum-ai/odinson/pull/287#discussion_r631374601

@BeckySharp @marcovzla - I'm using two randomly selected documents from `ai.lum.odinson.utils.TestUtils.ExampleDocs`. It looks like those are already parsed into Odinson json so it's hard to tell what the actual text is. Is there a generic rule you normally use that will work for any document?

2021-05-18 18:49 UTC, reynoldsm88 commented
@BeckySharp @marcovzla so i did some investigating into how `Lucene` internally handles incremental reads and writes. It turns out that there is a [special class provided by Lucene](https://lucene.apache.org/core/6_6_6/core/org/apache/lucene/search/SearcherManager.html) that is used to wrap and manage the lower level API's like `IndexWriter` and `IndexSearcher` for this very purpose.

I've stubbed out a POC using this `Lucene` API that shows how to do incremental indexing. There is a test that validates the approach. Note this is only from a `Lucene` perspective, we would need to integrate these changes to `Odinson` to validate that it will work with an `ExtractorEngine`:
[IncrementalLuceneIndex](https://github.com/reynoldsm88/odinson/blob/797456eb9823be62091d6d5b1f4ea13cba4f44f1/core/src/main/scala/ai/lum/odinson/lucene/LuceneIndex.scala#L30)
[TestLuceneIndex](https://github.com/reynoldsm88/odinson/blob/797456eb9823be62091d6d5b1f4ea13cba4f44f1/core/src/test/scala/ai/lum/odinson/lucene/TestLuceneIndex.scala#L15)

Based on my findings, my suggestion would be to refactor some of the code such that the `Odinson` classes do not interact with low level `Lucene` API's such as `IndexSearcher`. Instead, I would propose that we wrap `Lucene` functionality into an interface similar to what I have stubbed out here. In this way, we can create multiple implementation and include one that properly delegates functionality to the incremental indexing utilities.

I am happy to work on this, but I would like you to review the proof of concept I have stubbed out to make sure you understand and agree with my proposal.

2021-10-04 21:36 UTC, closed without merging