Metadata query language
lum-ai/odinson pull request #305
Opened 2021-06-22 00:26 UTC by BeckySharp

@marcovzla  and I worked on a query language for the metadata.
This supports:
- Dates
- Numbers
- strings
- regex over strings
- nested fields (e.g., people, where you want to match against attributes of a metadata field without mixing)

Other:
- tests added and older tests related to metadata queries updated.
- made slight change from #281 in terms of getting the field name and type for the metadata docs -- getting from a constant variable in `OdinsonIndexWriter` rather than the config for simplicity.
- added access methods in `ExtractorEngine` for `mkQuery` and `mkFilteredQuery` (i.e., the query + parent/metadata query), updated the tests to use this as example to outside world.

2021-06-22 18:25 UTC, myedibleenso reviewed
Great!  

The tests help illustrate features, but I think this calls for revisions to our documentation before merging.  We should provide a small overview of the language and correct prior mentions that claim the parent/metadata query is a Lucene query and instructions for preparing the metadata in the Odinson Document (ex. are there restrictions on field types?).

We also should change the API spec (a yaml file in the backend project), routes file, and param names for the corresponding method(s).  

Are we going to call this a metadata query now?  If so, I'd like to change some of the documentation in the REST API to reflect that convention.

2021-06-22 18:25 UTC, myedibleenso commented on backend/test/controllers/OdinsonControllerSpec.scala
>          // See http://www.lucenetutorial.com/lucene-query-syntax.html
We should remove this comment, as it's no longer relevant.

2021-06-24 17:16 UTC, danebell requested changes
My only request is that the key `parentDocFieldFileName` be available in `reference.conf`. Otherwise, this looks great.

2021-06-29 19:45 UTC, danebell commented
Merging in tests that rely on [`ExtractorEngine.getParentDoc`](https://github.com/lum-ai/odinson/blob/metadata/core/src/main/scala/ai/lum/odinson/ExtractorEngine.scala#L214-L228), it seems that the changes to `getParentDoc` make it crash because no documents ever match. I believe this is because it anticipates that the document ID will be part of the metadata, when in practice, it's outside the metadata group in the JSON.

2021-07-02 20:56 UTC, BeckySharp commented on core/src/main/resources/reference.conf
> -    parentDocFieldFileName = fileName
addressed with #304, right?

2021-07-02 21:00 UTC, BeckySharp commented
> Great!
> 
> The tests help illustrate features, but I think this calls for revisions to our documentation before merging. We should provide a small overview of the language and correct prior mentions that claim the parent/metadata query is a Lucene query and instructions for preparing the metadata in the Odinson Document (ex. are there restrictions on field types?).

@myedibleenso , we added documentation for the Metadata queries (`metadata.md`).

> We also should change the API spec (a yaml file in the backend project), routes file, and param names for the corresponding method(s).

Are we to do this? or will you/ @danebell ?

> Are we going to call this a metadata query now? If so, I'd like to change some of the documentation in the REST API to reflect that convention.

Yes, I think we should call them metadata queries, as it's more true to their semantics, `parent` is more about the implementation in lucene.

2021-07-03 04:51 UTC, myedibleenso commented
@danebell , can you take a look at this and take a first pass on updating the backend (API, routes file, tests, and OpenAPI spec)?  We should probably replace mentions of `parentQuery` with`metadataQuery`.

2021-07-05 21:20 UTC, danebell commented on core/src/main/resources/reference.conf
> -    parentDocFieldFileName = fileName
The fieldname is now available, but as referenced in my [other comment](https://github.com/lum-ai/odinson/pull/305#issuecomment-870866868), `getParentDoc` is not working as expected. If I see an obvious solution while working on #312 I'll apply it.

2021-07-07 00:32 UTC, merged